config/routes.rb
Berkleyproject::Application.routes.draw do
  devise_for :users

  root :to => 'pages#home'
  get 'about'=> 'pages#about'
  get 'photography' => 'pages#photography'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end

  def photography
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<!-- this text changes color on mouseover -->
	<p onmouseout="this.style.color = 'LightGray';" onmouseover="this.style.color = 'white';"> 
		<small>Written using skills learned from the 
			<em><u><%= link_to "One Month Rails", "http://www.onemonthrails.com" %></u></em> 
			course
		</small>.</p>
</div>

app/views/layouts/_header.html.erb
<div class="header">

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
   
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
   
        <!-- Be sure to leave the brand out there if you want it shown -->
        <!-- Button to trigger modal -->
        <a href="#myModal" role="button" class="brand" data-toggle="modal">Sam Jordan</a>

        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
        	<ul class="nav">
        		<li><%= link_to "Home", root_path %></li>
  					<li><%= link_to "About Me", about_path %></li>
            <li><%= link_to "Photography", photography_path %></li>
      	 </ul>
          
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <div>
                <li><%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-small" %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-small" %></li>
               </div> 
            <% else %>
              <div><li><%= link_to "Login", new_user_session_path, class:"btn btn-small" %></li></div> 
            <% end %>   
         </ul>

        </div>
   
      </div>
    </div>
  </div>
  <!-- Modal -->
            <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="color:black">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Hello!</h3>
              </div>
              <div class="modal-body">
                <p>Thanks for visiting my site. Would you like to know more about me?</p>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">No Thanks</button>
                <%= link_to "About Me", about_path, class:"btn btn-primary" %>
              </div>
            </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="background">
<head>
  <title>Berkley project</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class= "container">
		<div class= "hero-unit">
			<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class:"alert alert-#{name}") %>
			<% end %>
			<div class="body">
				<%= yield %>
			</div>
		</div>
			<%= render 'layouts/footer' %>
	</div>
</body>
</div>
</html>

app/views/pages/about.html.erb
<h1>about</h1>
<p>about me</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<div>
<p>
	Welcome to my site! If you haven't already, you can <%= link_to "Sign up here!", new_user_registration_path, class:"btn btn-success"%>
</p>
</div>

app/views/pages/photography.html.erb
<h1>Photography</h1>
<div><BR></div>
<script>
$('.carousel').carousel({
  interval: 2000
})
</script>
<div>
	<div id="myCarousel" class="carousel slide" data-interval="">
	  <!-- Carousel items -->
	  <div class="carousel-inner">
	    <div class="active item"><img src="http://i.imgur.com/TeeT4aj.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/cGZCCsL.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/ZRf9uat.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/lRQnCjW.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/qaaARQp.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/4Rj2MLv.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/I8pJBHO.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/ew7rmjY.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/9PhAk0Z.jpg" alt></div>
	    <div class="item"><img src="http://i.imgur.com/79sOsZg.jpg" alt></div>
	  </div>
	  <!-- Carousel nav -->
	  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>
</div>